# .github/workflows/coveralls.yml

name: Test Coveralls

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm test

      # Add steps to set up your Node.js environment and to run your test suite
      # to produce the LCOV coverage report file here

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # If you have specific files to upload, specify them here:
          files: "coverage/lcov.info"
